### ISSUE TITLE
Regular expression is not correct for testing ".db."

### ISSUE THREAD

**Issue by tagrudev** [GroundMeteor/localstorage#2]
There is a problem with testing the name of the collection with ".db."

```javascript
/.db./.test("feedbacks")
// returns true should be false
```

**Comment by raix** [comment]
Thanks, should be `/\.db\./.test("feedbacks")`

Ref:
https://github.com/GroundMeteor/localstorage/blob/master/client.js#L132

**Comment by tagrudev** [comment]
@raix I've made a pull request thanks :)

**Comment by raix** [comment]
Published ground:db@0.3.7
